"""Config loading: static registry (devnets.yaml) and per-devnet discovered cache."""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

import yaml


def repo_root() -> Path:
    """Return the repo root: the directory containing config/ and devnets/."""
    # This file lives at <repo_root>/devnets/config.py
    return Path(__file__).parent.parent.resolve()


def load_registry() -> dict[str, Any]:
    """Parse config/devnets.yaml and return it as a dict."""
    path = repo_root() / "config" / "devnets.yaml"
    if not path.exists():
        print(f"error: registry not found at {path}", file=sys.stderr)
        sys.exit(1)
    with path.open() as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        print("error: config/devnets.yaml is malformed", file=sys.stderr)
        sys.exit(1)
    return data


def resolve_devnet(name: str | None) -> str:
    """
    Return the target devnet name.
    Priority: explicit arg > DEVNET env var > registry default.
    Exits with an error if nothing resolves.
    """
    if name and name.strip():
        return name.strip()
    env_val = os.environ.get("DEVNET", "").strip()
    if env_val:
        return env_val
    registry = load_registry()
    default = registry.get("default", "")
    if default:
        return str(default)
    print(
        "error: no devnet specified; pass a devnet name, set DEVNET, "
        "or set 'default' in config/devnets.yaml",
        file=sys.stderr,
    )
    sys.exit(1)


def devnet_entry(name: str) -> dict[str, Any]:
    """
    Return the registry entry for the given devnet name.
    Exits with an error if the devnet is not in the registry.
    """
    registry = load_registry()
    devnets = registry.get("devnets", {})
    if name not in devnets:
        known = ", ".join(devnets.keys()) if devnets else "(none)"
        print(
            f"error: devnet '{name}' not found in config/devnets.yaml. "
            f"Known devnets: {known}",
            file=sys.stderr,
        )
        sys.exit(1)
    return dict(devnets[name])


def load_cache(name: str) -> dict[str, Any] | None:
    """
    Parse config/devnets/<name>.yaml and return it as a dict, or None if absent.
    """
    path = repo_root() / "config" / "devnets" / f"{name}.yaml"
    if not path.exists():
        return None
    with path.open() as f:
        data = yaml.safe_load(f)
    return data if isinstance(data, dict) else None


def write_cache(name: str, data: dict[str, Any]) -> None:
    """Dump data to config/devnets/<name>.yaml (YAML format)."""
    dir_path = repo_root() / "config" / "devnets"
    dir_path.mkdir(parents=True, exist_ok=True)
    path = dir_path / f"{name}.yaml"
    header = (
        f"# Auto-generated by: dv discover {name}\n"
        f"# Regenerate at any time with: dv discover {name}\n\n"
    )
    with path.open("w") as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def roster(name: str) -> list[str]:
    """
    Return the list of node names for the given devnet.

    Sources (in priority order):
    1. cache roster[].name entries
    2. 'roster' list in the registry entry (if present)
    3. Error telling the user to run 'dv discover <name>'
    """
    cache = load_cache(name)
    if cache and cache.get("roster"):
        nodes = cache["roster"]
        result = []
        for entry in nodes:
            if isinstance(entry, dict):
                n = entry.get("name", "")
            else:
                n = str(entry)
            if n:
                result.append(n)
        if result:
            return result

    # Fallback: registry entry may have a 'roster' list
    try:
        entry = devnet_entry(name)
        reg_roster = entry.get("roster", [])
        if reg_roster:
            return [str(n) for n in reg_roster]
    except SystemExit:
        pass

    print(
        f"error: no roster found for '{name}'. "
        f"Run 'dv discover {name}' to populate config/devnets/{name}.yaml",
        file=sys.stderr,
    )
    sys.exit(1)


def node_list(name: str, node_arg: str | None) -> list[str]:
    """
    Return [node_arg] if a specific node is given, else the full roster (for all/None).
    """
    if node_arg and node_arg.lower() != "all":
        return [node_arg]
    return roster(name)


# Default ethpandaops SSH host pattern. Placeholders: {user}, {node}, {devnet}.
# Override per devnet via the `ssh_host_template` field in config/devnets.yaml.
DEFAULT_SSH_HOST_TEMPLATE = "{user}@{node}.srv.{devnet}.ethpandaops.io"
DEFAULT_SSH_USER = "devops"


def is_ethrex_node(conn: Any, devnet: str, node: str) -> bool:
    """
    Return True if the node runs ethrex.

    Checks the latest node_health.image for that node (golden rule 4: prefer
    the live image). Falls back to checking whether "ethrex" appears in the
    node name when no health row is available.
    """
    try:
        row = conn.execute(
            """SELECT image FROM node_health
               WHERE devnet=? AND node=?
               ORDER BY ts DESC LIMIT 1""",
            (devnet, node),
        ).fetchone()
        if row and row["image"]:
            return "ethrex" in row["image"].lower()
    except Exception:
        pass
    return "ethrex" in node.lower()


def host_of(name: str, node: str) -> str:
    """
    Return the SSH host string for a node in a devnet.

    Uses the per-devnet `ssh_host_template` / `ssh_user` from config/devnets.yaml
    if present, else the ethpandaops default `devops@<node>.srv.<devnet>.ethpandaops.io`.
    """
    try:
        entry = devnet_entry(name)
    except Exception:
        entry = {}
    template = entry.get("ssh_host_template", DEFAULT_SSH_HOST_TEMPLATE)
    user = entry.get("ssh_user", DEFAULT_SSH_USER)
    return template.format(user=user, node=node, devnet=name)
